#!/bin/bash

jenkinsServer="ec2-34-240-28-128.eu-west-1.compute.amazonaws.com"
jenkinsPort="8080"
if [[ -z $jenkinsPort ]]
then
	jenkinsURL=${jenkinsServer}
else
	jenkinsURL="${jenkinsServer}:${jenkinsPort}"
fi
jobname=$1
token=$(./getAPIToken)

CRUMB=$(curl -s "http://${jenkinsURL}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)" -u admin:${token})

if ! curl -X POST ${jenkinsURL}/job/${jobname}/build \
  --user admin:${token} \
  --data-urlencode json='{"parameter": [{"name":"id", "value":"123"}, {"name":"verbosity", "value":"high"}]}'
then
	echo "Unable to run job"
	exit 1
fi
