#!/bin/bash

curl -sk -u admin:secret http://ec2-34-240-28-128.eu-west-1.compute.amazonaws.com:8080/user/admin/configure | grep -o 'apiToken.*</td>' | egrep -o 'value="[0-9A-Za-z]{1,}"' | awk -F= '{print $2}' | sed 's/"//g'
