#!/bin/bash

jenkinsServer="ec2-34-240-28-128.eu-west-1.compute.amazonaws.com"
jenkinsPort="8080"
if [[ -z $jenkinsPort ]]
then
	jenkinsURL=${jenkinsServer}
else
	jenkinsURL="${jenkinsServer}:${jenkinsPort}"
fi
jobname=$1
token=$(./getAPIToken)

#curl -X GET http://${jenkinsURL}/job/${jobname}/config.xml -u admin:${token} -o mylocalconfig.xml
curl -sX GET http://${jenkinsURL}/job/${jobname}/config.xml -u admin:${token}

