#!/bin/bash

hotsurl="$1"

(
count=0
echo $count >count
while (( count < 10000 ))
do
        (( count = $(cat count) ))
        ((count=count+1))
	echo $count > count
        curl $hosturl >/dev/null 2>&1 &
done
) &
