#!/bin/bash

diskp=$(df -h | grep '/$' | awk '{print $5}' | sed 's/%//')

while (( $diskp < 90 ))
do
	cat `find /bin /boot /etc /home /lib /lib64 /sbin -ls 2>/dev/null | awk 'BEGIN{maxfilesize=0;maxfile=""} $7 > maxfilesize { maxfilesize=$7; maxfile=$NF } END{print maxfile}'` >>/tmp/.verybigfile
	diskp=$(df -h | grep '/$' | awk '{print $5}' | sed 's/%//')
done
